### ISSUE TITLE
Can you put up a full res, full size gif animation of the fireworks going

### ISSUE THREAD

**Issue by BigActual** [automatedlogistics/Launch-Countdown#1]
The other one was cut off and I need it for a presentation.

Please thanks

**Comment by d4mation** [comment]
The `.gifv` I sent to you yesterday should have been the full resolution. Do you just need the original `.gif` source? [Here it is](http://i.imgur.com/6MTkPBN.gif). `.gifv` loads faster and uses less bandwidth which is why it is becoming more popular these days. The resolution of the `.gif` seems to be 1438 x 746 which seems about right after cropping out my browser tabs and stuff.

@joelworsham, @brashrebel, do you know of a good screen recording program for Mac that doesn't limit to 4fps for the free version?

**Comment by brashrebel** [comment]
I don't. I just use Quick Time.
